Algoritmo "A10EX1"
// Disciplina   : Lógica de Programação e Algoritmos
// Professor   : MSc. Tiago Antonio da Silva 
// Descrição   : Um algoritmo que le o nome da pessoa e exibe
// Autor(a)    : Jose Antonio Geraldo Felix
// Data atual  : 11/04/2025
Var

nome : caracter

Inicio

Escreval("Bom dia, Qual o seu nome?")
Escreva("Nome:")
Leia(nome)

Escreval("Bem-vindo(a), nobre ", nome," do Reino da Lógica!")

Fimalgoritmo