Algoritmo "Tabuada"
// Disciplina   : Lógica de Programação e Algoritmos
// Professor   : MSc. Tiago Antonio da Silva
// descrisção   :
// Autor(a)    : Jose Antonio Geraldo Felix
// Data atual  : 29/03/2025
// Data em que adicionei a descrisção nos exercicios
// antigos
Var

   i : inteiro
   numero : inteiro

Inicio

   Escreval("Você quer saber a tabuada de qual número ?")
   Leia(numero)

   Para i de 1 até 10 faca
      Escreval(i, " x", numero, " =", (i*numero) )
   fimpara

Fimalgoritmo