Algoritmo " A10EX7"
// Disciplina   : Lógica de Programação e Algoritmos
// Professor   : MSc. Tiago Antonio da Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Jose Antonio Geraldo Felix
// Data atual  : 12/04/2025
Var

   i : inteiro
   moeda : inteiro


Inicio

   Escreval("Quer contar quantas moedas ?")
   leia(moeda)

   para i de 1 ate moeda faca

      Escreval(i," Moedas")

   fimpara

   Escreval("Voce contou", moeda," Moedas")
Fimalgoritmo