Algoritmo "A10EX8"
// Disciplina   : Lógica de Programação e Algoritmos
// Professor   : MSc. Tiago Antonio da Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Jose Antonio Geraldo Felix
// Data atual  : 12/04/2025
Var

senha : caracter
certa : caracter

Inicio

certa <- "abracadabra"

repita

Escreval("Para abrir a porta magica acerte a senha")
leia(senha)

até senha = certa

Escreval("Voce abriu a porta")

Fimalgoritmo